project_id = "pyfdocfoahwjvjvlfbwd"

[functions.manage-templates]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.manage-org]
verify_jwt = false

[functions.whatsapp-onboarding]
verify_jwt = false

[functions.billing]
verify_jwt = false

[functions.send-campaign]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.ai-reply]
verify_jwt = false

[functions.send-reply]
verify_jwt = false

[functions.ai-insights]
verify_jwt = false

[functions.run-automations]
verify_jwt = false

[functions.execute-flow]
verify_jwt = false

[functions.fire-webhook]
verify_jwt = false

[functions.api-gateway]
verify_jwt = false

[functions.launch-scheduled]
verify_jwt = false

[functions.dpdp-manage]
verify_jwt = false

[functions.message-status-callback]
verify_jwt = false

[functions.debug-webhook]
verify_jwt = false
