project_id = "pyfdocfoahwjvjvlfbwd"

[functions.manage-templates]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.manage-org]
verify_jwt = false
